### ISSUE TITLE
Documentation on Rate limiting is false

### ISSUE THREAD

**Issue by nixon-transak** [covalenthq/covalent-docs#93]
**Note: This is about the API reference, which doent appear to be in this repo. I'm filling here anyway, as this is the best place I can find to do it. Please let me know where you would like reports on this kind of issue**

In your docs on [rate limiting](https://www.covalenthq.com/docs/api/#overview--rate-limiting) you say

> Rate limiting
>
> Not enforced at present. Please let us know before you melt our servers!

However, when I make a large ammount of requests, I get [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429), ie rate limiting.

**Comment by nixon-transak** [comment]
Eg

```python
import asyncio
import aiohttp


async def get(sess, block_height, chain_id=1):
    async with sess.get(
        f"https://api.covalenthq.com/v1/{chain_id}/block_v2/{block_height}/"
    ) as resp:
        assert resp.status == 200, resp
        return await resp.json()


async def main():
    async with aiohttp.ClientSession(auth=aiohttp.BasicAuth(COVALENT_KEY)) as session:
        tasks = []
        for i in range(10000):
            tasks.append(asyncio.ensure_future(get(session, i)))

        out = await asyncio.gather(*tasks)
        print(out)


asyncio.run(main())
```

Outputs

```
Traceback (most recent call last):
  File "/home/nixon/work/summer-internship-2021/covalent/rlim.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nixon/work/summer-internship-2021/covalent/rlim.py", line 20, in main
    out = await asyncio.gather(*tasks)
  File "/home/nixon/work/summer-internship-2021/covalent/rlim.py", line 10, in get
    assert resp.status == 200, resp
AssertionError: <ClientResponse(https://api.covalenthq.com/v1/1/block_v2/454/) [429 Too Many Requests]>
<CIMultiDictProxy('Date': 'Wed, 21 Jul 2021 11:45:30 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'CF-Cache-Status': 'BYPASS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=bjaarJJv95pgXv2bf2tKDeGU8iezafyb1r2tVH7x6sZA3fX606cgfqUcX1EqDfeNEWGwah7T3AirhTNq%2FNIHa3i39D1eHNiOWOPRFsEKYqmZ1G8aqOcihz%2ButekoNz9cOlUUTA%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"report_to":"cf-nel","max_age":604800}', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '67242ef51c683601-MAN', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400')>
```

**Comment by harishraisinghani** [comment]
Thanks and you're correct, the API reference needs to be updated. We're actually doing a full rebuild which will be live in just a couple weeks!

**Comment by anadi2311** [comment]
Currently, we don't have a rate limit but we do have a concurrent request limit of 20 req/ sec with a provision to increase if someone requests more. @emmaodia please make the change it creates confusion
